name: Build

on:
  push:
    branches: [ "main-cpp" ]
  pull_request:
    branches: [ "main-cpp" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
          - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++"
          }
          - {
            name: "macOS Latest Intel",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }
          - {
            name: "macOS Latest ARM",
            os: macos-14,  # M1/M2/M3 runner
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v3

    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install openssl --version=3.1.1 -y
        dir "C:\Program Files\OpenSSL-Win64"
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" | Out-File -Append -FilePath $env:GITHUB_ENV
        echo "OPENSSL_LIBRARIES=C:\Program Files\OpenSSL-Win64\lib" | Out-File -Append -FilePath $env:GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL-Win64\include" | Out-File -Append -FilePath $env:GITHUB_ENV

    - name: Install OpenSSL (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev

    - name: Install OpenSSL (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install openssl@3
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        cmake -B build ^
        -G "Visual Studio 17 2022" ^
        -A x64 ^
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
        -DOPENSSL_ROOT_DIR="${{env.OPENSSL_ROOT_DIR}}" ^
        -DOPENSSL_LIBRARIES="${{env.OPENSSL_LIBRARIES}}" ^
        -DOPENSSL_INCLUDE_DIR="${{env.OPENSSL_INCLUDE_DIR}}" ^
        -DOPENSSL_USE_STATIC_LIBS=ON

    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare artifacts (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir artifact
        copy build\bin\${{env.BUILD_TYPE}}\*.exe artifact\
        copy build\bin\${{env.BUILD_TYPE}}\*.dll artifact\

    - name: Prepare artifacts (Unix)
      if: runner.os != 'Windows'
      run: |
        mkdir artifact
        cp build/bin/* artifact/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}-binaries
        path: artifact/
        retention-days: 7
